FROM registry.fedoraproject.org/fedora-toolbox:latest
RUN sudo dnf install -y go git-lfs &&\
  curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.5.0
