# permissions:
#   contents: write
#   pull-requests: write

on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: go
          # path: setup/
      - name: Setup Go
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
      - name: Build go and upload
        if: ${{ steps.release.outputs.release_created }}
        working-directory: ./setup/
        run: |
          go download
          for arch in amd64, arm64, arm32
          do
            GOARCH=$arch go build -o jelp-$GOOS-$arch
            gh release upload ${{ steps.release.outputs.tag_name }} jelp-linux-$arch
          done
        env:
            GOOS: linux