permissions:
  contents: write

on:
  push:
    branches:
      - master
    paths:
      - setup/version.txt
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build go
        run: |
          cd setup
          go mod download
          for arch in amd64 arm64; do
            echo -e "$arch\n"
            GOARCH=$arch go build -o jest-$GOOS-$arch
          done
        env:
            GOOS: linux
      - name: Build release file
        run: git log $(git show HEAD~1:setup/version.txt)..HEAD --pretty=format:"- %s (%h)" > release.md
      # - name: Update Change Log
      #   run: echo -e "# $(cat setup/version.txt)\n$(cat release.md)\n$(cat CHANGELOG.md)" > CHANGELOG.md
      - name: Create release
        run: gh release create $(cat setup/version.txt) -F release.md ./setup/jest-*
        env:
          GH_TOKEN: ${{ github.token }}
        